name: CI
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Install dependencies
        run: corepack yarn setup
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test --coverage
      - name: Build
        run: yarn build
